name: MasterDeployCI
on:
    push:
        branches:
            - master
jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [12.x]
        steps:
            - uses: actions/checkout@v1
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}
            - name: Install Packages
              run: npm install
            - name: Deploy to GH Pages
              env:
                  GITHUB_TOKEN: ${{secrets.SECRET_TOKEN}}
                  API_KEY: ${{secrets.API_KEY}}
                  MONGODB_URI: ${{secrets.MONGODB_URI}}
              run: |
                  git config --global user.email "cristiano.vinhal10@gmail.com"
                  git config --global user.name "csvinhal"
                  git remote set-url origin https://$GITHUB_ACTOR:$GITHUB_TOKEN@github.com/$GITHUB_REPOSITORY.git
                  npm run deploy
